apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-discovery
  name: spring-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-discovery
    spec:
      containers:
        - image: tihlok/spring-discovery:latest
          name: spring-discovery
          ports:
            - containerPort: 8761
