apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-gateway
  name: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-gateway
    spec:
      containers:
        - image: tihlok/spring-gateway:latest
          name: spring-gateway
          ports:
            - containerPort: 8761
